response: Bot Response
search_phrase: Term to search for
twitter: { 
  access_token_key: your_access_token_key, 
  access_token_secret: your_access_token_secret,
  consumer_key: your_consumer_key, 
  consumer_secret: your_consumer_secret,
  since_id: 0 }
